### ISSUE TITLE
Issues with IDA Pro 7.4

### ISSUE THREAD

**Issue by taogoldi** [Cisco-Talos/DynDataResolver#2]
I know that this plug in was only tested on IDA Pro 7.2. However, I am getting the following error in IDA pro 7.4:

C:\Program Files\IDA Pro 7.4\plugins\ddr_plugin.py: module 'idaapi' has no attribute 'Choose2'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 593, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.4/plugins/ddr_plugin.py", line 1375, in <module>
    class DDR_MyChoose2(idaapi.Choose2):
AttributeError: module 'idaapi' has no attribute 'Choose2'

Wondering if anyone reported this previously. Please advise.

**Comment by hunterbr72** [comment]
Sorry for the late answer, this is known, we are releasing a new version this or next week latest. That one will support the latest IDA version.
